GET http://localhost:8080/api/health

###
GET http://localhost:8080/api/error

###
POST http://localhost:8080/api/customer

{
    "first_name": "John",
    "last_name": "Doe",
    "birthday": "1990-01-01T00:00:00Z",
    "email": "john.doe@example.com",
    "phone": "+420605401050",
    "state": "Vsetín",
    "address": "123 Main St"
}

###
GET http://localhost:8080/api/customer

###
GET http://localhost:8080/api/customer/c671d852-567e-4724-b3c1-a4f1d0773a7a

###
PUT http://localhost:8080/api/customer/48d5716a-c7b4-4551-bfb8-c78c40dab36c

{
    "first_name": "Tobiáš",
    "last_name": "Filgas",
    "birthday": "1990-01-01T00:00:00Z",
    "email": "john.doe@example.com",
    "phone": "+420605401050",
    "state": "Vsetín",
    "address": "123 Main St"
}

###
DELETE http://localhost:8080/api/customer/23508041-e7f6-421f-9267-7e2c3762f2aa

###
POST http://localhost:8080/api/customer/d56a10bc-2fa6-4605-9e6c-c403c3da89e8/account

{
  "Balance": 1000.00,
  "Type": 1,
  "Currency": "USD"
}

###
GET http://localhost:8080/api/customer/d56a10bc-2fa6-4605-9e6c-c403c3da89e8/account

###
GET http://localhost:8080/api/customer/d56a10bc-2fa6-4605-9e6c-c403c3da89e8/account/99fd0672-6d4b-46d2-9641-ab21a8ebd52c

###
PUT http://localhost:8080/api/customer/d56a10bc-2fa6-4605-9e6c-c403c3da89e8/account/99fd0672-6d4b-46d2-9641-ab21a8ebd52c

{
  "Balance": 1000.00,
  "Type": 4,
  "Currency": "USD",
  "Status": false,
  "LastTransactionDate": "2024-04-19T12:00:00Z",
  "InterestRate": 0.025
}

###
DELETE http://localhost:8080/api/customer/d56a10bc-2fa6-4605-9e6c-c403c3da89e8/account/99fd0672-6d4b-46d2-9641-ab21a8ebd52c
