GET http://localhost:8080/api/health

###
GET http://localhost:8080/api/error

###
POST http://localhost:8080/api/customer

{
    "first_name": "John",
    "last_name": "Doe",
    "birthday": "1990-01-01T00:00:00Z",
    "email": "john.doe@example.com",
    "phone": "+420605401050",
    "state": "New York",
    "address": "123 Main St"
}

